### ISSUE TITLE
Unclear where x-auth-header is

### ISSUE THREAD

**Issue by DS-Koala** [bcanfield/southpaw#56]
Can you show how to find the x-auth-header in both Chrome and Firefox? Here's a screenshot of what my dev console looks like; I don't know where to find the necessary info.

![Fanduel_ss](https://github.com/bcanfield/southpaw/assets/93602059/60dba20d-31b7-4dc5-a860-158291fb067f)

**Comment by bcanfield** [comment]
There’s been a lot of interest in this library so I’m going to be pushing
out some more details on the readme later. Once you login to FanDuel
through their website, it will be the “authorization” header.
